services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    volumes:
      - ./tunnel:/etc/cloudflared
    env_file:
      - .env