// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermalPrinterWeb.Services.Journal;

#nullable disable

namespace ThermalPrinterWeb.Services.Journal.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    partial class JournalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ThermalPrinterWeb.Services.Journal.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ByteCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaperDots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReprintOf")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("ThermalPrinterWeb.Services.Journal.PrintJobPayload", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Blocks")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlainText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Request")
                        .HasColumnType("BLOB");

                    b.HasKey("JobId");

                    b.ToTable("PrintJobPayloads");
                });

            modelBuilder.Entity("ThermalPrinterWeb.Services.Journal.PrintJobPayload", b =>
                {
                    b.HasOne("ThermalPrinterWeb.Services.Journal.PrintJob", null)
                        .WithOne("Payload")
                        .HasForeignKey("ThermalPrinterWeb.Services.Journal.PrintJobPayload", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThermalPrinterWeb.Services.Journal.PrintJob", b =>
                {
                    b.Navigation("Payload")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
